### ISSUE TITLE
Error:  undefined method `each_key'

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-archives#54]
On **Jekyll** `master` **jekyll-archives** throws an error.

```text
Error:  undefined method `each_key' for Jekyll::Drops::UnifiedPayloadDrop:Jekyll::Drops::UnifiedPayloadDrop
```

Full trace:
```text
~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-cc5937815e3a/lib/jekyll/utils.rb:33:in `deep_merge_hashes!': undefined method `each_key' for Jekyll::Drops::UnifiedPayloadDrop:Jekyll::Drops::UnifiedPayloadDrop (NoMethodError)
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-cc5937815e3a/lib/jekyll/utils.rb:20:in `deep_merge_hashes'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-archives-40823a4e16d8/lib/jekyll-archives/archive.rb:100:in `render'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-archives-40823a4e16d8/lib/jekyll-archives.rb:104:in `block in render'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-archives-40823a4e16d8/lib/jekyll-archives.rb:103:in `each'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-archives-40823a4e16d8/lib/jekyll-archives.rb:103:in `render'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-archives-40823a4e16d8/lib/jekyll-archives.rb:48:in `generate'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-cc5937815e3a/lib/jekyll/site.rb:154:in `block in generate'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-cc5937815e3a/lib/jekyll/site.rb:153:in `each'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-cc5937815e3a/lib/jekyll/site.rb:153:in `generate'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-cc5937815e3a/lib/jekyll/site.rb:58:in `process'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-cc5937815e3a/lib/jekyll/command.rb:28:in `process_site'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-cc5937815e3a/lib/jekyll/commands/build.rb:60:in `build'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-cc5937815e3a/lib/jekyll/commands/build.rb:35:in `process'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-cc5937815e3a/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from ~/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from ~/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from ~/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from ~/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from ~/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from ~/.rvm/gems/ruby-2.1.2/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from ~/.rvm/gems/ruby-2.1.2/bundler/gems/jekyll-cc5937815e3a/bin/jekyll:17:in `<top (required)>'
	from ~/.rvm/gems/ruby-2.1.2/bin/jekyll:23:in `load'
	from ~/.rvm/gems/ruby-2.1.2/bin/jekyll:23:in `<main>'
	from ~/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from ~/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

The problem is [here](https://github.com/jekyll/jekyll-archives/blob/master/lib/jekyll-archives/archive.rb#L100)

This is likely a problem with Jekyll rather than **jekyll-archives**, and I am working to write some sort of failing test to investigate this.

**Comment by pathawks** [comment]
Closed via jekyll/jekyll#4289
