### ISSUE TITLE
Error: undefined method `page', when plugin used with Jekyll 3.1.pre.beta1

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll-archives#55]
@parkr Thought it worth noting that using the pre-release of Jekyll 3.1 will break builds that use this plugin. The following error is provided:

```
/Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.1.0.pre.beta1/lib/jekyll/convertible.rb:248:in `do_layout': undefined method `page' for #<Hash:0x007fbbdadb0b80> (NoMethodError)
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives/archive.rb:104:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:104:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:48:in `generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.1.0.pre.beta1/lib/jekyll/site.rb:154:in `block in generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.1.0.pre.beta1/lib/jekyll/site.rb:153:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.1.0.pre.beta1/lib/jekyll/site.rb:153:in `generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.1.0.pre.beta1/lib/jekyll/site.rb:58:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.1.0.pre.beta1/lib/jekyll/command.rb:28:in `process_site'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.1.0.pre.beta1/lib/jekyll/commands/build.rb:60:in `build'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.1.0.pre.beta1/lib/jekyll/commands/build.rb:35:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.1.0.pre.beta1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/gems/jekyll-3.1.0.pre.beta1/bin/jekyll:17:in `<top (required)>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by parkr** [comment]
Bug reporter extraordinaire!!!!!!!!!! :heart: 

We'll have this fixed up for ya soon. :)

**Comment by alfredxing** [comment]
We'll have to move this over to use Drops as well. I'll see if I can get to it today!

**Comment by parkr** [comment]
This is because Utils.deep_merge_hashes returns a hash instead of a drop when the first parameter is a hash. Convertible and Renderer should be changed to use the hash syntax instead of the object method syntax.
