### ISSUE TITLE
Undefined method `extname' in Jekyll 3.3

### ISSUE THREAD

**Issue by artlogic** [jekyll/jekyll-archives#74]
I just upgrade to Jekyll 3.3 and I'm seeing this traceback:

```
/Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/lib/jekyll/renderer.rb:38:in `block in converters': undefined method `extname' for #<Jekyll::Archives::Archive:0x007fcff59184b8> (NoMethodError)
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/lib/jekyll/renderer.rb:38:in `select'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/lib/jekyll/renderer.rb:38:in `converters'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/lib/jekyll/renderer.rb:68:in `run'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/lib/jekyll/convertible.rb:211:in `do_layout'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-archives-2.1.0/lib/jekyll-archives/archive.rb:104:in `render'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:104:in `block in render'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `each'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `render'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:48:in `generate'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/lib/jekyll/site.rb:174:in `block in generate'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/lib/jekyll/site.rb:172:in `each'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/lib/jekyll/site.rb:172:in `generate'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/lib/jekyll/site.rb:68:in `process'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/lib/jekyll/command.rb:26:in `process_site'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/lib/jekyll/commands/build.rb:63:in `build'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/lib/jekyll/commands/serve.rb:37:in `block (2 levels) in init_with_program'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/gems/jekyll-3.3.0/exe/jekyll:13:in `<top (required)>'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/bin/jekyll:23:in `load'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/bin/jekyll:23:in `<main>'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/bin/ruby_executable_hooks:15:in `eval'
	from /Users/artlogic/.rvm/gems/ruby-2.3.0@voltdocs/bin/ruby_executable_hooks:15:in `<main>'
```

I'm not sure if this is an issue with Jekyll or Jekyll Archives, but since other things seem to be working, I'm assuming the problem is here.

**Comment by pathawks** [comment]
Known issue. This is fixed in the `master` branch. Just need to release a new gem.

**Comment by artlogic** [comment]
Thanks @pathawks! I assume that'll be happening soon.
