### ISSUE TITLE
`block in converters': undefined method `extname' when using with Jekyll 3.3

### ISSUE THREAD

**Issue by paulrobertlloyd** [jekyll/jekyll-archives#75]
Hello,

Just updated to Jekyll 3.3, and it appears there might be an incompatibility with this plugin. Here's the full trace:

```sh
JEKYLL_ENV=development bundle exec jekyll build --config etc/jekyll.yml --future --trace --profile
Configuration file: etc/jekyll.yml
                    Caching is disabled by configuration. However, if you're using proxies, a cache might still be created.
            Source: ./src
       Destination: ./www
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    Caching is disabled by configuration. However, if you're using proxies, a cache might still be created.
/Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/renderer.rb:38:in `block in converters': undefined method `extname' for #<Jekyll::Archives::Archive:0x007f9a9ecf3880> (NoMethodError)
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/renderer.rb:38:in `select'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/renderer.rb:38:in `converters'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/renderer.rb:68:in `run'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/convertible.rb:211:in `do_layout'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives/archive.rb:104:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:104:in `block in render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `render'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:48:in `generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:174:in `block in generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:172:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:172:in `generate'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/site.rb:68:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/command.rb:26:in `process_site'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/commands/build.rb:63:in `build'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/jekyll-3.3.0/exe/jekyll:13:in `<top (required)>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `load'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `<main>'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
rake aborted!
Command failed with status (1): [JEKYLL_ENV=development bundle exec jekyll ...]
/Users/paulrobertlloyd/Sites/paulrobertlloyd/Rakefile:22:in `block in <top (required)>'
/Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/paulrobertlloyd/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => build-dev
```

Is there anything that may have changed in 3.3 to cause this error @parkr/@alfredxing?

**Comment by ashmaroli** [comment]
using `master` branch of this repo will solve this..
Ref: [this comment](https://github.com/jekyll/jekyll/issues/5417#issuecomment-251764277)

**Comment by paulrobertlloyd** [comment]
@ashmaroli Oh, I hadn’t seen that thread. Will close this comment and continue any discussion over there. Thanks!

**Comment by miklb** [comment]
I appreciate that a fix is in master, but any timeline for when the gem will be updated?

**Comment by DirtyF** [comment]
@miklb watch #76 ;)
