### ISSUE TITLE
Undefined method `extname` in Jekyll 3.4.3

### ISSUE THREAD

**Issue by mckeever02** [jekyll/jekyll-archives#98]
Hi,
I saw the issues with this with Jekyll 3.3.0 but I'm experiencing it in the latest version. I'm using Jekyll Archives 2.1.0.

Here's the full trace when I run `jekyll build`:

```
/Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/lib/jekyll/renderer.rb:38:in `block in converters': undefined method `extname' for #<Jekyll::Archives::Archive:0x007fab078c3408> (NoMethodError)
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/lib/jekyll/renderer.rb:38:in `select'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/lib/jekyll/renderer.rb:38:in `converters'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/lib/jekyll/renderer.rb:68:in `run'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/lib/jekyll/convertible.rb:211:in `do_layout'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives/archive.rb:104:in `render'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:104:in `block in render'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `each'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:103:in `render'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-archives-2.1.0/lib/jekyll-archives.rb:48:in `generate'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/lib/jekyll/site.rb:174:in `block in generate'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/lib/jekyll/site.rb:172:in `each'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/lib/jekyll/site.rb:172:in `generate'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/lib/jekyll/site.rb:68:in `process'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/lib/jekyll/command.rb:26:in `process_site'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:63:in `build'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/gems/jekyll-3.4.3/exe/jekyll:13:in `<top (required)>'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/bin/jekyll:23:in `load'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/bin/jekyll:23:in `<main>'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/mckeever02/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

Any ideas why it isn't working?

Thanks

**Comment by mckeever02** [comment]
Sorry, my mistake. Manually updating the gem to `2.1.1` using `gem update jekyll-archives` has fixed the issue.
